### PR TITLE
Fix popup not working in Private Browsing contexts

### PR DESCRIPTION
**Pull request by laniakea64**
Fixes https://github.com/ACK-J/Port_Authority/issues/11

### CODE REVIEW

**Comment by ACK-J** [comment]
You are the best! Thanks for the help

**Comment by ACK-J** [comment]
@laniakea64 Hey shoot me an email! 
https://www.g666gle.me/contact

**Comment by laniakea64** [comment]
Thanks for the invitation @ACK-J but unfortunately I really can't afford more time atm, sorry.

**Comment by ACK-J** [comment]
@laniakea64 Understood, thanks for the help!

**Pull request merged**
