### PR TITLE
Update regex in background.js

### PR DESCRIPTION
**Pull request by Dorsalus**
Changed regex to match IPv6 enclosed in square brackets, only looks for opening bracket. Current match is optional so both formats; [fc03:49bd:b7c1:5685::2] and fc03:49bd:b7c1:5685::2, are postively matched.

### CODE REVIEW

**Comment by ACK-J** [comment]
Hey question. Is there any reason there is a open brackey but no closed bracket in the last group of the regex? `\[?[fF][eE][89aAbB][0-9a-fA-F](?:[:][0-9a-fA-F]{0,4}){0,7})`

**Comment by ACK-J** [comment]
Modifications and changes made in v. 1.0.19 https://github.com/ACK-J/Port_Authority/commit/7af3a737b4abedadb1bbaa0b88ed07d675b15d95

**Comment by Dorsalus** [comment]
I was getting some strange behaviour with the closing bracket for some reason but looks like you've fixed it.

**Comment by Dorsalus** [comment]
Thanks for the partial credit btw, it's appreciated.

**Comment by ACK-J** [comment]
Thanks for the help!

**Pull request closed without merging**
